openapi: 3.0.0
info:
  title: Customer Limit Update Encrypted
  description: >
    Encrypted - Limit Update API to decrease Phoenix customer limit
    (called by SCB)
  contact:
    name: Credit Risk
  version: 2.0.0
servers:
  - description: domain name within VPN
    url: https://combined-credit-limit-service.apps.{env}.nonprod.c0.phx-infra.com/customer-limit/{version}/
    variables:
      version:
        description: The Open API endpoints are accessible via **https** only
        enum:
          - v1
        default: v1
      env:
        enum:
          - dev
          - stg
          - prod
        default: dev
paths:
  /limit-update:
    post:
      security:
        - accessTokenAuth: []
      summary: update customer credit limit
      operationId: updateCustomerCreditLimit
      description: This endpoint is to decrease PHX customer credit limit
      parameters:
        - in: header
          name: requestId
          schema:
            type: string
          required: true
        - in: header
          name: x-encrypted
          schema:
            type: boolean
            default: true
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/limitUpdateRequest"
      responses:
        "200":
          description: Customer Credit Limit Decreased
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ack"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "408":
          $ref: "#/components/responses/RequestTimeout"
        "500":
          $ref: "#/components/responses/InternalError"
        "503":
          $ref: "#/components/responses/ServiceUnavailable"
        "504":
          $ref: "#/components/responses/GatewayTimeout"
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    accessTokenAuth:
      type: http
      scheme: bearer
  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            type: object
            required:
              - errorCode
            properties:
              errorCode:
                type: string
                description: refer to error code list per API
              debugMessage:
                type: string
              validationErrors:
                additionalProperties:
                  type: object
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            required:
              - errorCode
            properties:
              errorCode:
                type: string
                description: refer to error code list per API
              debugMessage:
                type: string
              validationErrors:
                additionalProperties:
                  type: object
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            type: object
            required:
              - errorCode
            properties:
              errorCode:
                type: string
                description: refer to error code list per API
              debugMessage:
                type: string
              validationErrors:
                additionalProperties:
                  type: object
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            type: object
            required:
              - errorCode
            properties:
              errorCode:
                type: string
                description: refer to error code list per API
              debugMessage:
                type: string
              validationErrors:
                additionalProperties:
                  type: object
    RequestTimeout:
      description: Request Timeout
      content:
        application/json:
          schema:
            type: object
            required:
              - errorCode
            properties:
              errorCode:
                type: string
                description: refer to error code list per API
              debugMessage:
                type: string
              validationErrors:
                additionalProperties:
                  type: object
    InternalError:
      description: Internal error
      content:
        application/json:
          schema:
            type: object
            required:
              - errorCode
            properties:
              errorCode:
                type: string
                description: refer to error code list per API
              debugMessage:
                type: string
              validationErrors:
                additionalProperties:
                  type: object
    ServiceUnavailable:
      description: Service Unavailable
      content:
        application/json:
          schema:
            type: object
            required:
              - errorCode
            properties:
              errorCode:
                type: string
                description: refer to error code list per API
              debugMessage:
                type: string
              validationErrors:
                additionalProperties:
                  type: object
    GatewayTimeout:
      description: Gateway Timeout
      content:
        application/json:
          schema:
            type: object
            required:
              - errorCode
            properties:
              errorCode:
                type: string
                description: refer to error code list per API
              debugMessage:
                type: string
              validationErrors:
                additionalProperties:
                  type: object
  schemas:
    limitUpdateRequest:
      type: object
      required:
        - payload
      properties:
        payload:
          type: string
          description: |
            contains encrypted request string
    ack:
      type: object
      title: trustCustomerLimitDetails
      required:
        - payload
      properties:
        payload:
          type: string
          description: |
            contains encrypted response string
    serviceResponse:
      type: object
      properties:
        code:
          type: string
          description: Service Response code
        description:
          type: string
          description: Service response description
    errors:
      description: List of error object
      type: array
      items:
        $ref: "#/components/schemas/error"
    error:
      description: Error object details
      title: error
      required:
        - id
        - code
        - detail
      type: object
      properties:
        id:
          description: The X-requestId from the request header, if the transaction id was
            not present in the request header, a generated random UUID will
            be  shown here for tracking purposes.
          type: string
        code:
          description: an application-specific error code
          type: string
        detail:
          description: a human-readable explanation specific to this occurrence of the
            problem
          type: string
        source:
          description: reference to the source of the error. e.g. a URI query parameter
            caused the error or an attribute in the request object
          type: string
    gatewayerror:
      description: API Gateway Error object details
      title: API Gateway Error
      required:
        - msgId
        - errCd
        - errMsg
      type: object
      properties:
        msgId:
          description: The unique message id identify this particular API call
          type: string
        errCd:
          description: an internal error code
          type: string
        errMsg:
          description: a human-readable explanation specific to this occurrence of the
            problem
          type: string

